# Updated .gitlab-ci.yml for C++ projects with both server and client binaries

image: gcc:latest

variables:
  CLIENT_BINARY: "SageStoreClient"
  SERVER_BINARY: "SageStoreServer"

before_script:
  - apt-get update -qq
  - apt-get install -y -qq software-properties-common
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
  - apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - apt-get update -qq
  - apt-get install -y -qq cmake

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - echo "There are no tests!"


deploy:
  stage: deploy
  script:
    - echo "There is no deployment script"
  environment:
    name: SageStore

