# .gitlab-ci.yml for C++ SageStore project
# This configuration is currently set up to build only the server.
# Client build is skipped for now.

image: gcc:latest

variables:
  SERVER_BINARY: "SageStoreServer"

before_script:
  # Setting up dependencies for server build
  - apt-get update -qq
  - apt-get install -y -qq cmake

stages:
  - build_server # Stage for building only the server
  - test
  - deploy

build_server: # Job for building only the server
  stage: build_server
  script:
    - mkdir build
    - cd build
    - cmake ../Server # Specify the Server directory to build only the server part
    - make
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - echo "There are no tests!"

deploy:
  stage: deploy
  script:
    - echo "There is no deployment script"
  environment:
    name: SageStore
