@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define entity(x) class x << (E,#D5E1DD) >>

entity("Roles") {
  + RoleID : int
  --
  Name : string
}

entity("Users") {
  + UserID : int
  --
  Username : string
  Password : string
  RoleID : int
}

entity("UserLogs") {
  + LogID : int
  --
  UserID : int
  Action : string
  Timestamp : datetime
}

entity("Contacts") {
  + ContactID : int
  --
  Name : string
  Type : string
  Email : string
  Phone : string
}

entity("ContactDetails") {
  + ContactDetailsID : int
  --
  ContactID : int
  name : string
  value : string
}

entity("EmployeeRecords") {
  + EmployeeID : int
  --
  Name : string
}

entity("Suppliers") {
  + SupplierID : int
  --
  Name : string
  Contact : string
  Email : string
}

entity("ProductType") {
  + TypeID : int
  --
  CatalogueCode : string
  Barcode : string
  UKT_ZED : string
  Unit : string
  IsImported : bool
  SupplierID : int
}

entity("Products") {
  + ProductID : int
  --
  Name : string
  Description : string
  Category : string
  ProductTypeID : int
  EmployeeRecordID: int
}

entity("Inventory") {
  + InventoryID : int
  --
  ProductID : int
  UserID : int
  QuantityAvailable : int
}

entity("Orders") {
  + OrderID : int
  --
  Date : datetime
  UserID : int
  CustomerID : int
  Status : string
  Type : string
  OrderDetailID : int
}

entity("OrderDetails") {
  + OrderDetailID : int
  --
  OrderID : int
  ProductID : int
  Quantity : int
  Price : float
}

entity("PurchaseOrders") {
  + PurchaseOrderID : int
  --
  Date : datetime
  UserID : int
  SupplierID : int
  OrderDetailID : int
  Status : string
}

Roles "1" -- "0..*" Users : has
Users "1" -- "0..*" UserLogs : has
Users "1" -- "0..*" Orders : placed
Users "1" -- "0..*" PurchaseOrders : placed
Users "1" -- "0..*" Inventory : manages
EmployeeRecords "1" -- "0..*" Orders : involved_in
EmployeeRecords "1" -- "0..*" Products : has
Contacts "1" -- "0..*" ContactDetails : has
Contacts "1" -- "0..*" Orders : involved_in
Contacts "1" -- "0..*" PurchaseOrders : involved_in
Suppliers "1" -- "0..*" ProductType : supplies
ProductType "1" -- "0..*" Products : categorizes
Products "1" -- "0..*" Inventory : stored_in
Products "1" -- "0..*" OrderDetails : involved_in
Orders "1" -- "0..*" OrderDetails : consists_of
PurchaseOrders "1" -- "0..*" OrderDetails : consists_of
@enduml