@startuml

!define RECTANGLE class
!define INTERFACE interface

' Main Application Service
RECTANGLE SageStoreServer {
  +start(): void
}

' Mediator Interface
INTERFACE IMediator {
  +mediate()
}

' Mediators
RECTANGLE SalesInventoryMediator {
  +mediate()
}

RECTANGLE UserManagementMediator {
  +mediate()
}

RECTANGLE EmployeeClientManagementMediator {
  +mediate()
}

RECTANGLE AnalyticsMediator {
  +mediate()
}

IMediator <|-- SalesInventoryMediator
IMediator <|-- UserManagementMediator
IMediator <|-- EmployeeClientManagementMediator
IMediator <|-- AnalyticsMediator

' API Endpoints
package "API Endpoints" {
  RECTANGLE APIFacade {
    +route(requestType, requestData): void
  }
  RECTANGLE Endpoints {
    +RESTful APIs
    +RPC Endpoints
  }

  APIFacade -- Endpoints
}

' Relationships for API Endpoints
SageStoreServer -up-> APIFacade : uses

' Business Logic
package "Business Logic" {
  RECTANGLE BusinessLogic {
    +init(): void
  }

  INTERFACE IBusinessModule {
    +init(): void
  }

  package "Modules" {
    RECTANGLE SalesModule
    RECTANGLE InventoryModule
    RECTANGLE HRModule
    RECTANGLE CustomerManagementModule
    RECTANGLE UserManagementModule
    RECTANGLE SupplierManagementModule
    RECTANGLE AnalyticsModule
  }
}

' Data Access Layer
package "Data Access Layer" {
  RECTANGLE DatabaseManager {
    +connect(): void
    +disconnect(): void
  }

  INTERFACE IRepository {
    +insert(): void
    +update(): void
    +delete(): void
    +query(): void
  }

  package "Repositories" {
    RECTANGLE UserManagementRepository
    RECTANGLE UserLogsRepository
    RECTANGLE ContactsRepository
    RECTANGLE EmployeeRecordsRepository
    RECTANGLE SuppliersRepository
    RECTANGLE ProductTypeRepository
    RECTANGLE ProductsRepository
    RECTANGLE InventoryRepository
    RECTANGLE OrdersRepository
    RECTANGLE OrderDetailsRepository
    RECTANGLE PurchaseOrdersRepository
  }
}

' Hidden relationships for layout control
InventoryModule -[hidden]- SalesModule
HRModule -[hidden]- InventoryModule
CustomerManagementModule -[hidden]- HRModule
UserManagementModule -[hidden]- CustomerManagementModule
SupplierManagementModule -[hidden]- UserManagementModule
AnalyticsModule -[hidden]- SupplierManagementModule

' Relationships for Main Application Service
SageStoreServer -down-> BusinessLogic : uses
SageStoreServer -down-> DatabaseManager : uses
SageStoreServer -down-> IMediator : uses

' Relationships for Mediators to Packages
IMediator -down-> IBusinessModule : uses
IMediator -down-> IRepository : uses

' Relationships for Business Logic
BusinessLogic -down-> IBusinessModule : uses

' Relationships for Data Access Layer
DatabaseManager -down-> IRepository : uses

' Repositories
"Repositories" -down-> IRepository : implements

' Business Modules
"Modules" -down-> IBusinessModule : implements

@enduml
