version: 2.1

jobs:
  clone_repo:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

  install_prerequisites:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install -y python3-pip
            sudo apt-get install -y python3-pip gcc g++ cmake make git libgl-dev libgl1-mesa-dev xkb-data
            # sudo apt-get install -y build-essential cmake ninja-build pkg-config \
            #             libgl1-mesa-dev libx11-dev libxkbcommon-dev libwayland-dev \
            #             libsqlite3-dev libssl-dev zlib1g-dev libbz2-dev \
            #             libpng-dev libharfbuzz-dev libbrotli-dev
            # sudo apt-get install -y libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev \
            #             libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev \
            #             libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev \
            #             libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev \
            #             libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev \
            #             libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-present-dev \
            #             libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev        
            # sudo apt-get install -y libxcb-util-dev    

      - run:
          name: Install Conan
          command: |
            pip3 install conan  # Use pip3 to ensure Python 3's pip is used
      - run:
          name: Setup Conan
          command: |
            conan profile detect 

  build_project:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run CMake with presets and build the project
          command: |
            conan install . --output-folder=build --build=missing -s compiler.cppstd=20 -c tools.system.package_manager:mode=install
            cd build
            cmake .. --preset conan-debug -DBUILD_CLIENT=ON -DBUILD_SERVER=ON -DBUILD_TESTS=ON
            cmake --build .

  run_tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests using ctest
          command: |
            cd build
            ctest --verbose

workflows:
  version: 2
  build_and_test:
    jobs:
      - clone_repo
      - install_prerequisites:
          requires:
            - clone_repo
      - build_project:
          requires:
            - install_prerequisites
      - run_tests:
          requires:
            - build_project
