@startuml
skinparam componentStyle uml2

title SageStore Client (Current)

package "SageStore Client" {
    [main.cpp] as MAIN
    [DialogManager] as DM
    [MainWindow] as MW

    package "Users Management MVVM" {
        [UsersManagementModel] as UMM
        [UsersManagementViewModel] as UMVM
        [UsersView] as UV

        UMM --> UMVM
        UMVM --> UV
    }

    [ApiManager] as API
    [NetworkService] as NET
    [JsonSerializer] as JSON

    MAIN --> DM
    MAIN --> MW
    MAIN --> API
    API --> NET
    NET --> JSON

    MW --> UMM
    MW --> UMVM
    MW --> UV
    DM --> API
}

@enduml
