@startuml

class SageStoreClient {
    -m_uiManager: UiManager
    ...
}

class UiManager {
    -m_dialogManager: DialogManager
    ...
    -m_concreteModel: ConcreteModel 
    ... <<other Models>>
    -m_concreteViewModel: ConcreteViewModel
    ... <<other ViewModels>>
    -m_concreteView: ConcreteView
    ... <<other Views>>
}

interface BaseModel {
}

interface IViewModel {
}

interface BaseView {
}

interface BaseDialog {
}

class DialogManager {
    -m_loginDialog: LoginDialog
    ... <<other Dialogs>>
}

class LoginDialog implements BaseDialog {
}

class ConcreteModel implements BaseModel {
}

class ConcreteViewModel implements IViewModel {
}

class ConcreteView implements BaseView {
}

SageStoreClient -->  UiManager

UiManager -->  ConcreteModel
UiManager  -->  ConcreteViewModel
UiManager  -->  ConcreteView
UiManager -[hidden]right- IViewModel
UiManager -[hidden]right- BaseModel
UiManager -[hidden]right- BaseView
UiManager  --> DialogManager

DialogManager  --> LoginDialog
DialogManager -[hidden]left- BaseDialog

@enduml
