@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define entity(x) class x << (E,#D5E1DD) >>

entity("Roles") {
  + RoleID : int
  --
  Name : string
}

entity("Users") {
  + UserID : int
  --
  Username : string
  Password : string
  RoleID : int
}

entity("UserLogs") {
  + LogID : int
  --
  UserID : int
  Action : string
  Timestamp : datetime
}

entity("Contacts") {
  + ContactID : int
  --
  Name : string
  Type : string
  Email : string
  Phone : string
}

entity("ContactInfo") {
  + ContactInfoID : int
  --
  ContactID : int
  Name : string
  Value : string
}

entity("Employees") {
  + EmployeeID : int
  --
  Name : string
  Number : string
  Email : string
  Address : string
}

entity("Suppliers") {
  + SupplierID : int
  --
  Name : string
  Number : string
  Email : string
  Address : string
}

entity("ProductType") {
  + ProductTypeID : int
  --
  CatalogueCode : string
  Barcode : string
  UKT_ZED : string
  Name : string
  Description : string
  Category : string
  LastPrice : float
  Unit : string
  IsImported : bool
}

entity("ProductTypeSupplierInfo") {
  + ProductTypeSupplierInfoID : int
  --
  ProductTypeID : int
  Code : string
  SupplierID : int
}

entity("Inventory") {
  + InventoryID : int
  --
  ProductTypeID : int
  QuantityAvailable : int
  EmployeeID : int
}

entity("SaleOrders") {
  + OrderID : int
  --
  Date : datetime
  UserID : int
  ContactID : int
  EmployeeID : int
  Status : string
  OrderInfoID : int
}

entity("OrderInfo") {
  + OrderInfoID : int
  --
  OrderID : int
  ProductTypeID : int
  Quantity : int
  Price : float
}

entity("PurchaseOrders") {
  + PurchaseOrderID : int
  --
  Date : datetime
  UserID : int
  SupplierID : int
  Status : string
  OrderInfoID : int
}

Roles "1" -- "0..*" Users : asigned to
Users "1" -- "0..*" UserLogs : has
Users "1" -- "0..*" SaleOrders : create
Users "1" -- "0..*" PurchaseOrders : create
Employees "1" -- "0..*" Inventory : own
Contacts "1" -- "0..*" ContactInfo : has
Contacts "1" -- "0..*" SaleOrders : buy
Suppliers "1" -- "0..*" ProductType : supplies
ProductType "1" -- "0..*" ProductTypeSupplierInfo : has
ProductType "1" -- "0..*" Inventory : stored_in
ProductType "1" -- "0..*" OrderInfo : involved_in
SaleOrders "1" -- "0..*" OrderInfo : consists_of
PurchaseOrders "1" -- "0..*" OrderInfo : consists_of
@enduml
