@startuml
!define entity(x) class x << (E,#D5E1DD) >>

title Database Schema (Current)

entity("Role") {
  + id : int
  --
  name : string
}

entity("User") {
  + id : int
  --
  username : string
  password : string
  roleId : int
}

entity("Log") {
  + id : int
  --
  userId : int
  action : string
  timestamp : datetime
}

entity("Contact") {
  + id : int
  --
  name : string
  type : string
  email : string
  phone : string
}

entity("ContactInfo") {
  + id : int
  --
  contactID : int
  name : string
  value : string
}

entity("Employee") {
  + id : int
  --
  name : string
  number : string
  email : string
  address : string
}

entity("Supplier") {
  + id : int
  --
  name : string
  number : string
  email : string
  address : string
}

entity("SuppliersProductInfo") {
  + id : int
  --
  supplierID : int
  productTypeId : int
  code : string
}

entity("ProductInfo") {
  + id : int
  --
  productTypeId : int
  name : string
  value : string
}

entity("ProductType") {
  + id : int
  --
  code : string
  barcode : string
  name : string
  description : string
  lastPrice : float
  unit : string
  isImported : bool
}

entity("Inventory") {
  + id : int
  --
  productTypeId : int
  quantityAvailable : int
  employeeId : int
}

entity("SaleOrder") {
  + id : int
  --
  date : datetime
  userId : int
  contactId : int
  employeeId : int
  status : string
}

entity("SalesOrderRecord") {
  + id : int
  --
  orderId : int
  productTypeId : int
  quantity : int
  price : float
}

entity("PurchaseOrder") {
  + id : int
  --
  date : datetime
  userId : int
  supplierId : int
  status : string
}

entity("PurchaseOrderRecord") {
  + id : int
  --
  orderId : int
  productTypeId : int
  quantity : int
  price : float
}

Role "1" -- "0..*" User : assigned to
User "1" -- "0..*" Log : has
User "1" -- "0..*" SaleOrder : creates
User "1" -- "0..*" PurchaseOrder : creates
Employee "1" -- "0..*" Inventory : owns
Contact "1" -- "0..*" ContactInfo : has
Contact "1" -- "0..*" SaleOrder : buys
ProductType "1" -- "0..*" ProductInfo
ProductType "1" -- "0..*" SuppliersProductInfo
Supplier "1" -- "0..*" SuppliersProductInfo
ProductType "1" -- "0..*" Inventory : stored_in
ProductType "1" -- "0..*" SalesOrderRecord : involved_in
SaleOrder "1" -- "0..*" SalesOrderRecord : consists_of
ProductType "1" -- "0..*" PurchaseOrderRecord : involved_in
PurchaseOrder "1" -- "0..*" PurchaseOrderRecord : consists_of
@enduml
