@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define entity(x) class x << (E,#D5E1DD) >>

entity("Roles") {
  + id : int
  --
  name : string
}

entity("Users") {
  + id : int
  --
  username : string
  password : string
  roleId : int
}

entity("Logs") {
  + id : int
  --
  userId : int
  action : string
  timestamp : datetime
}

entity("Contacts") {
  + id : int
  --
  name : string
  type : string
  email : string
  phone : string
}

entity("ContactInfo") {
  + id : int
  --
  contactID : int
  name : string
  value : string
}

entity("Employees") {
  + id : int
  --
  name : string
  number : string
  email : string
  address : string
}

entity("Suppliers") {
  + id : int
  --
  name : string
  number : string
  email : string
  address : string
}

entity("SuppliersProductInfo") {
  + id : int
  --
  supplierID : int
  productTypeId : int
  code : string
}

entity("ProductInfo") {
  + id : int
  --
  productTypeId : int
  name : string
  value : string
}

entity("ProductType") {
  + id : int
  --
  code : string
  barcode : string
  ukt_zed : string
  name : string
  description : string
  category : string
  lastPrice : float
  unit : string
  isImported : bool
}

entity("Inventory") {
  + id : int
  --
  productTypeId : int
  quantityAvailable : int
  employeeId : int
}

entity("SaleOrders") {
  + id : int
  --
  date : datetime
  userId : int
  contactId : int
  employeeId : int
  status : string
  orderInfoId : int
}

entity("OrderInfo") {
  + id : int
  --
  orderId : int
  productTypeId : int
  quantity : int
  price : float
}

entity("PurchaseOrders") {
  + id : int
  --
  date : datetime
  userId : int
  supplierId : int
  status : string
  orderInfoId : int
}

Roles "1" -- "0..*" Users : asigned to
Users "1" -- "0..*" Logs : has
Users "1" -- "0..*" SaleOrders : create
Users "1" -- "0..*" PurchaseOrders : create
Employees "1" -- "0..*" Inventory : own
Contacts "1" -- "0..*" ContactInfo : has
Contacts "1" -- "0..*" SaleOrders : buy
ProductType "1" -- "0..*" ProductInfo
ProductType "1" -- "0..*" SuppliersProductInfo
Suppliers "1" -- "0..*" SuppliersProductInfo
ProductType "1" -- "0..*" Inventory : stored_in
ProductType "1" -- "0..*" OrderInfo : involved_in
SaleOrders "1" -- "0..*" OrderInfo : consists_of
PurchaseOrders "1" -- "0..*" OrderInfo : consists_of
@enduml
