@startuml
skinparam componentStyle uml2

title SageStore Server (Current)

package "SageStore Server" {
    [SageStoreServer] as APP
    [HttpServer] as HTTP
    [HttpTransaction] as TX
    [JsonSerializer] as JSON

    [BusinessLogic] as BL
    [UsersModule] as UM
    [InventoryModule] as IM

    [RepositoryManager] as RM
    [UserRepository] as UR
    [RoleRepository] as RR
    [ProductTypeRepository] as PTR
    [SqliteDatabaseManager] as DB

    APP --> HTTP
    APP --> BL
    APP --> RM

    HTTP --> TX
    TX --> JSON
    TX --> BL : request-response

    BL --> UM
    BL --> IM

    UM --> UR
    UM --> RR
    IM --> PTR

    RM --> UR
    RM --> RR
    RM --> PTR
    UR --> DB
    RR --> DB
    PTR --> DB
}

@enduml
