@startuml
skinparam componentStyle uml2

package "SageStore Server" {
    [SageStoreServer] as SSS 
    [HttpServer] as HS 
    [HttpTransaction] as HT 
    [Serializers] as S 
    [BusinessLogic] as BLF 
    [BusinessModules] as BM 
    [RepositoriesManager] as RM
    [DatabaseManager] as DM
    [Repositories] as R  

    SSS -down-> HS 
    SSS -down-> BLF 
    SSS -down-> RM

    HS -down-> HT
    HT -down-> S 

    BLF -down-> BM
    HT <.> BLF : "request-response"

    RM -down-> R 
    R -down-> DM

    BM .> R : "read/write"

    note "Repository Pattern" as RepoNote1
    RepoNote1 .. R

    note "Facade Pattern" as RepoNote2
    RepoNote2 .. BLF
}

@enduml
