@startuml
skinparam componentStyle uml2

package "SageStore Server" {
    [SageStoreServer] as SSS 
    [HttpServer] as HSer 
    [HttpSession] as HSes 
    [Serializers] as S 
    [BusinessLogicFacade] as BLF 
    [BusinessModules] as BM 
    [Mediators] as M 
    [DatabaseManager] as DM
    [Repositories] as R  

    SSS -down-> HSer 
    SSS -down-> BLF 
    SSS -down-> DM

    HSer -right-> BLF : "executeTask"
    HSer <-right- BLF : "callback"

    HSer "1"-down->"1..*" HSes
    HSes "1"-down->"1" S 

    BLF "1"-down->"1..*" BM

    DM "1"-down->"1..*" R 

    BM -right-> M
    BM <-right- M 
    M -right-> R 
    M <-right- R

    note "Mediator Pattern" as MediatorNote
    MediatorNote .. M

    note "Repository Pattern" as RepoNote
    RepoNote .. R
}

@enduml
